on: [pull_request]

name: Dusk CI

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main
    with:
      clippy_default: false
      clippy_args: --release --features=rkyv-impl,rkyv/size_16 -- -D warnings

  dusk_analysis:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  check_no_std:
    name: check no_std
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo check --no-default-features --target thumbv6m-none-eabi
        
  test_std:
    name: Nightly std tests
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --features=rkyv-impl,rkyv/size_16,serde

  test_parallel:
    name: Nightly std tests parallel
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --features=parallel,rkyv-impl,rkyv/size_16,serde
